# Generated by Django 5.1.2 on 2024-10-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('option_1', models.CharField(max_length=100)),
                ('option_2', models.CharField(max_length=100)),
                ('option_3', models.CharField(max_length=100)),
                ('votes_1', models.IntegerField(default=0)),
                ('votes_2', models.IntegerField(default=0)),
                ('votes_3', models.IntegerField(default=0)),
            ],
        ),
    ]
